version: 1.0.{build}
os: Visual Studio 2013
init:
- git config --global core.autocrlf true
install:
- set PATH=C:\Program Files (x86)\MSBuild\12.0\Bin;%PATH%
before_build:
- nuget restore
build:
  project: AnagramCheck.sln
  verbosity: minimal
test_script:
- .\packages\OpenCover.4.6.247-rc\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"D:\GitHubNew\AnagramCheck\AnagramCheckUnitTests\bin\Debug\AnagramCheckUnitTests.dll -noshadow -appveyor" -returntargetcode -filter:"+[StyleCop*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*\*Designer.cs -hideskipped:All -output:.\AnagramCheck_coverage.xml
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "AnagramCheck_coverage.xml"
# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
cache:
  - packages -> **\packages.config