# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: AnagramCheck.sln      # path to Visual Studio solution or project
environment:
  COVERALLS_REPO_TOKEN:
    secure: 6x28xtKiwJ7f1WhYUrc6LQ1WG5QSn0pJQOHIolJ+zWDE7mqRAS5K1X/mbbi7w9C2
cache:
- src\packages -> **\packages.config
- C:\ProgramData\chocolatey\bin -> build.environment.ps1
- C:\ProgramData\chocolatey\lib -> build.environment.ps1
install:
- ps: .\build.environment.ps1
- ps: psake .\build.tasks.ps1 appveyor-install
build_script:
- ps: psake .\build.tasks.ps1 appveyor-build
test_script:
- ps: psake .\build.tasks.ps1 appveyor-test
artifacts:
- path: opencovertests.xml
  name: opencovertests.xml
- path: coveralls.net.*.zip
- path: coveralls.net.*.nupkg