os: Visual Studio 2013
build: off

environment:
  COVERALLS_REPO_TOKEN:
    secure: 6x28xtKiwJ7f1WhYUrc6LQ1WG5QSn0pJQOHIolJ+zWDE7mqRAS5K1X/mbbi7w9C2

before_test:
  - dotnet --info
  - dotnet restore

test_script:
  # Build sample
  - dotnet test AnagramCheckUnitTests/AnagramCheckUnitTests.csproj
  
after_test:
  # Build and pack source
  - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\OpenCover'))[0].FullName + '\tools\OpenCover.Console.exe' + ' -register:user -target:".\script\runtests.bat" -searchdirs:".\test\Qwack.Math.Tests\bin\Debug" -oldstyle -output:coverage.xml -skipautoprops -returntargetcode -filter:"+[Anagram*]* -[*Tests]* -[*Benchmark]*"')
  - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\coveralls.io'))[0].FullName + '\tools\coveralls.net.exe' + ' --opencover coverage.xml')
  
artifacts:
  path: '**/*.nupkg'
