# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: AnagramCheck.sln      # path to Visual Studio solution or project
# MSBuild verbosity level
  verbosity: minimal
