version: 1.0.0.{build}

configuration: ReleaseNoVsix

init:
  - git config --global core.autocrlf true

clone_folder: c:\projects\code-cracker

shallow_clone: false

clone_depth: 5

environment:
  COVERALLS_REPO_TOKEN:
    secure: 6x28xtKiwJ7f1WhYUrc6LQ1WG5QSn0pJQOHIolJ+zWDE7mqRAS5K1X/mbbi7w9C2

before_build:
  - ps: >-
      $env:path="C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files (x86)\MSBuild\12.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\VCPackages;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;$env:path"
      
      . .\build.ps1 Prepare-Build
      
     
build_script:
  - ps: . .\build.ps1 Build-Only


after_build:
  - ps: >-
      . .\build.ps1 Pack-Nuget
      
test_script:
  - ps: >-
      . .\build.ps1 Test
      
      
after_test:
  - ps: >-
      . ".\test\CSharp\AnalyzeCecil.ps1"
      
      
artifacts:
  - path: src
    name: src
  - path: test
    name: test
  - path: log
    name: log
