version: 4.6.{build}
skip_tags: true
os: Visual Studio 2013
shallow_clone: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: 6x28xtKiwJ7f1WhYUrc6LQ1WG5QSn0pJQOHIolJ+zWDE7mqRAS5K1X/mbbi7w9C2
cache:
- build/Version/opencover.snk
- build/Version/opencover.public.snk
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    if ($env:APPVEYOR_SCHEDULED_BUILD -eq "True" -or $env:APPVEYOR_REPO_BRANCH -eq "coverity") {
      & .\build.bat create-coverity-release
    } else {
      & .\build.bat create-release
    }
    
test: off
artifacts:
- path: main/bin/installer/*.msi
  name: Installer
- path: main/bin/zip/*.zip
  name: ZipArchive
- path: main/bin/packages/nuget/opencover/*.nupkg
  name: Nuget
- path: main/bin/packages/nuget/opencover-rc/*.nupkg
  name: NugetCandidate
- path: main/bin/packages/chocolatey/opencover/*.nupkg
  name: Chocolatey
- path: main/bin/packages/chocolatey/opencover.portable/*.nupkg
  name: ChocolateyPortable
on_success:
- ps: >-
    if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_SCHEDULED_BUILD -ne "True" -and $env:APPVEYOR_REPO_BRANCH -ne "coverity") {
      & .\build.bat sonarqube-build
    } else {
      & .\build.bat dogfood-release
    }